const ITERATIONS = 100;

const JSON_MODE = "JSON_MODE";
const SO_MODE = "SO_MODE";
const TOOL_CALL_WITH_FORCE_MODE = "TOOL_CALL_WITH_FORCE_MODE";
const TOOL_CALL_WITH_AUTO_MODE = "TOOL_CALL_WITH_AUTO_MODE";

const MODES = [
    JSON_MODE,
    SO_MODE,
    TOOL_CALL_WITH_FORCE_MODE,
    TOOL_CALL_WITH_AUTO_MODE
];

const OPENAI_4O_MINI_MODEL = "gpt-4o-mini";
const OPENAI_4O_MODEL = "gpt-4o";
const AZURE_OPENAI_4O_MINI_MODEL = "azure-gpt-4o-mini";
const AZURE_OPENAI_4O_MODEL = "azure-gpt-4o";

const MODELS = [
    AZURE_OPENAI_4O_MINI_MODEL,
    AZURE_OPENAI_4O_MODEL,
    OPENAI_4O_MINI_MODEL,
    OPENAI_4O_MODEL
];
